// Generated by CoffeeScript 1.3.3

define(["jquery", "underscore", "backbone", "router"], function($, _, backbone, router) {
  var initialize;
  initialize = function() {
    return router.initialize();
  };
  return {
    initialize: initialize
  };
});
