// Generated by CoffeeScript 1.3.3

define(["jquery", "underscore", "backbone", "views/render_links", "views/render_tags", "views/add_links"], function($, _, Backbone, renderLinksView, renderTags, addLinksView) {
  var AppRouter, initialize;
  AppRouter = Backbone.Router.extend({
    routes: {
      "*actions": "defaultRoute"
    },
    defaultRoute: function(actions) {
      console.debug("AppRouter:defaultRoute");
      return addLinksView.render();
    }
  });
  initialize = function() {
    var app_router;
    app_router = new AppRouter();
    return Backbone.history.start();
  };
  return {
    initialize: initialize
  };
});
