// Generated by CoffeeScript 1.3.3

define(["jquery", "underscore", "backbone", "syphon", "models/tag", "collections/tags", "text!templates/add/add_tags.hbs"], function($, _, Backbone, Syphon, TagModel, tagsCollection, addTagsTemplate) {
  var addTagsView;
  addTagsView = Backbone.View.extend({
    render: function() {}
  });
  return new addTagsView({
    el: $("add_tags")
  });
});
