// Generated by CoffeeScript 1.3.3

define(["jquery", "underscore", "handlebars", "backbone", "syphon", "mediator", "models/link", "models/tag", "text!templates/render/render_links.hbs"], function($, _, Handlebars, Backbone, Syphon, mediator, LinkModel, TagModel, renderLinksTemplate) {
  var RenderLinksView;
  RenderLinksView = Backbone.View.extend({
    initialize: function() {
      mediator.on('add:links_collection', this.render, this);
      return mediator.on('fetch:links_collection', this.renderInit, this);
    },
    render: function(link) {
      var data, template;
      data = {
        links: link.collection.toJSON()
      };
      template = Handlebars.compile(renderLinksTemplate);
      return $("#link-collections").html(template(data));
    },
    renderInit: function(links) {
      var data, template;
      data = {
        links: links
      };
      template = Handlebars.compile(renderLinksTemplate);
      return $("#link-collections").html(template(data));
    }
  });
  return new RenderLinksView({
    el: $("#link-collections")
  });
});
