// Generated by CoffeeScript 1.3.3

define(["underscore", "backbone"], function(_, Backbone) {
  var TagModel;
  TagModel = Backbone.Model.extend({
    defaults: {},
    initialize: function() {}
  });
  return TagModel;
});
