// Generated by CoffeeScript 1.3.3

define(["jquery", "underscore", "backbone", "local_storage", "models/tag"], function($, _, Backbone, LocalStorage, TagModel) {
  var TagsCollection;
  TagsCollection = Backbone.Collection.extend({
    model: TagModel,
    localStorage: new Backbone.LocalStorage("tags-backbone"),
    initialize: function() {}
  });
  return new TagsCollection;
});
